Repository ovh/rollup-plugin-less-inject, pull requests merged in 2019-06, with the labels that each got.

#4 docs(contributing): refer to the right project name
  CONTRIBUTING.md
Labels: documentation

#2 build: add .editorconfig file
  .editorconfig
Labels: build

#5 build: add prepare & prepublishOnly to package.json
  package.json
  rollup.config.js
Labels: bug
